trigger:
- main

resources:
- repo: self

variables:
  tag: 23 
  
  #'$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
   
    - task: DownloadPipelineArtifact@2
      inputs:
       buildType: 'current'
       artifactName: 'manifests'
       itemPattern: '**/*.yaml'
       targetPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: 'azure-resource-manager-service-connection'
        azureResourceGroup: 'kubernetes_dev'
        kubernetesCluster: 'k8stest_dev'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/deployment.yaml'
        containers: 'in28min/currency-exchange-devops:${tag}'

    #- task: Docker@2
     # inputs:
      #  containerRegistry: 'in28min-docker-hub'
       # repository: 'in28min/currency-exchange-devops'
        #command: 'buildAndPush'
        #Dockerfile: '**/Dockerfile'
        #tags: '$(tag)'
    - task: PublishBuildArtifacts@1
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'manifests'
       publishLocation: 'Container'
